export { default as Home } from './Home.jsx'
export { default as Services } from './Services.jsx'
export { default as About } from './About.jsx'
export { default as Clients } from './Clients.jsx'
export { default as Contact } from './Contact.jsx'
export { default as Projects } from './Projects.jsx'
export { default as News } from './News.jsx'